version: 0.2

phases:
   install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:webupd8team/java
      - apt-get update -y
      - apt-get install -y oracle-java8-installer
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws ecr get-login)
  build:
    commands:
      - mvn clean package    
  post_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simplewebapp .
      - docker tag simplewebapp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/simplewebapp:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/simplewebapp:latest